### ISSUE TITLE
[WANT] 닉네임 생성 시, 특수문자 제한 기능 요청.

### ISSUE THREAD

**Issue by KangBaekGwa** [1-screeningHumanity/TMT-BE-MemberServer#33]
## 요청 구분
- [ ] 신규 요구 사항 발생
- [x] 수정 요청

## 요청 내용
현재, 닉네임 생성 시, 특수문자 (/, *)등 관계없이 승인 되도록 설정되어있습니다.
이를, 특수문자는 허용 하지 않도록 설정 하도록 요청 드립니다.

## 예상 문제점
닉네임을 사용하는 pathvariable, queryString 사용 시, url path에 특수문자가 들어갈 시, 문제가 발생 할 수 있습니다.

**Comment by hoontaepark** [comment]
확인했습니다 추후 반영하겠습니다.
